
[functions.scan-food]
enabled = true
verify_jwt = true
import_map = "./functions/scan-food/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/scan-food/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/scan-food/*.html" ]

[functions.log-meal]
enabled = true
verify_jwt = true
import_map = "./functions/log-meal/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/log-meal/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/log-meal/*.html" ]

[edge_runtime]
enabled = true


[functions.log-exercise]
enabled = true
verify_jwt = true
import_map = "./functions/log-exercise/deno.json"
entrypoint = "./functions/log-exercise/index.ts"

[functions.submit-feedback]
enabled = true
verify_jwt = true
import_map = "./functions/submit-feedback/deno.json"
entrypoint = "./functions/submit-feedback/index.ts"

